Repository htw-pv3/literature, pull requests merged in 2020-04, with the labels that each got.

#1 Add starting bib file for shared literature
  shared_literature.bib
Labels: good first issue, help wanted

#4 Add example file to bibtex file #3
  shared_literature.bib
Labels: enhancement

#14 Add empty git_cheat_sheet.txt to document git commands #13
  git_cheat_sheet.txt
Labels: documentation, help wanted
