Repository htw-pv3/literature, pull requests merged in 2020-05, with the labels that each got.

#19 feature/cheatsheet_md add Cheatsheet for Markdown v1.0 #18
  Cheatsheet_MD.md
Labels: documentation, enhancement, help wanted

#17 Feature/add protocol 3
  2020-04-22-protocol-3.md
Labels: documentation, help wanted

#22 Cleaned up and Minor fixes
  Cheatsheet_MD.md
Labels: documentation, enhancement, help wanted

#28 add protocol 3 #11
  protokolle/2020-04-22_htw-pv3_software-session.md
Labels: documentation, enhancement

#24 Python codes23
  Python_BasicLiterature_MitBeispiel.md
Labels: documentation, enhancement, help wanted

#31 Add git_Cheat_Sheet.png to the directory (source: Huelk) #13
  git_Cheat_Sheet.png
Labels: documentation, enhancement, help wanted

#27 add protocol 2 #11
  protokolle/2020-04-15_htw-pv3_daten.md
Labels: review

#25 Feature/add protocol 4#11
  protokolle/2020-04-29_htw-pv3_postgresql.md
Labels: documentation, enhancement

#34 added PV-weblinks.md and filled with websources #32
  README.md
  git_literature.md
  shared_literature_PV_FE.bib
Labels: enhancement, help wanted

#37 GitBash_Code_So_Far_#10
  Codes_GitBash_So_Far.md
Labels: documentation, good first issue, help wanted, review

#42 Feature/basic python codes
  Python_BasicLiterature_MitBeispiel.md
Labels: documentation, enhancement, good first issue

#41 Add checkboxes to the markdown crib sheet
  crib-cheat_markdown.md
Labels: documentation, enhancement, review

#46 add literature #45
  shared_literature_PV_FE.bib
Labels: documentation, review

#44 Adding Protocol 2020-05-06 (#43)
  protokolle/2020-05-06_htw-pv3_postgresql_II.md
  protokolle/2020-06-06_htw-pv3_postgresql_II.md
Labels: documentation, enhancement, invalid, review

#51 Adding_SQL-commands_#50
  SQL/SQL.md
Labels: documentation

#49 add git tutorials -#48
  git_literature.md
Labels: documentation, good first issue

#53 add official PostgreSQL-cheat-sheet #38
  SQL/PostgreSQL-Cheat-Sheet.pdf
Labels: enhancement, review

#55 Adding_Postgis_Enabling_Code
  SQL/PostGis_Enabling.md
Labels: documentation
