Repository htw-pv3/literature, pull requests merged in 2021-04, with the labels that each got.

#72 Feature 70 linebreak
  crib-cheat_git.md
Labels: good first issue

#77 fix missing command #76
  crib-cheat_git.md
Labels: documentation, good first issue

#78 issue#75
  crib-cheat_git.md
Labels: documentation, good first issue

#79 changed line 135, "esr" into "es" #74
  crib-cheat_git.md
Labels: documentation, good first issue

#87 Feature 86 space
  crib-cheat_git.md
Labels: good first issue

#89 Add missing brackets #88
  crib-cheat_python.md
Labels: good first issue

#99 Line 39 going to Going changed. Issue #97.
  crib-cheat_git.md
Labels: documentation, good first issue

#98 line 30 - change ")" to "," - #96
  crib-cheat_git.md
Labels: documentation, good first issue

#95 Correct typo #91
  crib-cheat_markdown.md
Labels: documentation, good first issue

#102 Feature 100 postges
  .gitignore
  crib-cheat_postgres.md
Labels: documentation, enhancement

#103 New Git Command added #101
  crib-cheat_git.md
Labels: documentation, good first issue

#106 Corrected typo in line 128 #104
  crib-cheat_git.md
Labels: good first issue

#81 Remove triple header #80
  crib-cheat_git.md
Labels: documentation, good first issue

#83 Feature 82 typo
  crib-cheat_git.md
Labels: documentation, good first issue

#118 Feature 117 typo
  .gitignore
  crib-cheat_git.md
  crib-cheat_postgres.md
Labels: good first issue

#109 PostgreSQL version update in literature/references.bib #105
  references.bib
Labels: documentation, enhancement, good first issue
