Repository htw-pv3/literature, pull requests merged in 2022-04, with the labels that each got.

#140 add cloneguide #138
  crib-cheat_git.md
Labels: documentation, enhancement, good first issue

#147 Grammatical correction of CONTRIBUTING.md file #146
  CONTRIBUTING.md
Labels: documentation

#151 Feature 150 typo markdownmd
  CONTRIBUTING.md
  README.md
  crib-cheat_git.md
  crib-cheat_markdown.md
  crib-cheat_postgres.md
  crib-cheat_python.md
  references.bib
Labels: documentation

#149 Feature 148 typo line54 vrib cheat
  crib-cheat_git.md
Labels: good first issue

#168 Spelling of Comiting has been changed into Comitting #155
  crib-cheat_git.md
Labels: documentation, enhancement, good first issue
