Repository htw-pv3/literature, pull requests merged in 2025-04, with the labels that each got.

#252 Update Meld-Version auf 3.22.2 #250
  references.bib
Labels: review

#253 PostgreSQL Version updated from 13.2 to 17.4 #223
  references.bib
Labels: enhancement

#243 rename "crib-cheat" to "crib-sheet"
  crib-sheet_git.md
  crib-sheet_markdown.md
  crib-sheet_postgres.md
  crib-sheet_python.md
Labels: wontfix, tutorial
